### ISSUE TITLE
Equality of ms(0) and ms(-1) when using multiple bases

### ISSUE THREAD

**Issue by plesiecki** [kristoferjoseph/modular-scale#1]
Hello, 

One thing bothers me. When I use multiple bases like `1, 0.875` the ms(0) and ms(-1) are equal. I noticed this is [expected behaviour](https://github.com/kristoferjoseph/modular-scale/blob/master/test.js#L38-L39). But according to [modularscale.com](http://www.modularscale.com/?0.875,1&em&1.25&web&text) with the exact same configuration ms(0) is higher/bigger than ms(-1).

Any thoughts on this matter?

**Comment by kristoferjoseph** [comment]
Been thinking I should probably revisit this so that you can specify steps _below_ the base using negative numbers, but at the time I wrote this library I was attempting to keep the code as similar to the ruby implementation as possible. It has seemed to diverge a bit since then so I no longer feel tethered to this restriction.

**Comment by kristoferjoseph** [comment]
OK I fixed this and am much happier with the code... SO MUCH EASIER TO FOLLOW!
Caveat is that now you can only specify one base and one ratio per instance of modularScale ( which makes it much easier to reason about and use imho )

Thanks for taking the time to file an issue, sorry it took my YEARS to come back to it.
kj💕
